[book]
authors = ["Kaio Felipe"]
language = "en"
description = "Learn how to use Inertia with Rust to build single-page apps!"
src = "src"
title = "Inertia Rust"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/KaioFelps/inertia-rust/tree/v2?b=v2"
site-url = "/inertia-rust/"

[output.html.playground]
runnable = false
