name: Cargo Clippy

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: warn

jobs:
  check_linting:
    name: "assert rust-clippy patterns are followed"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
  check_code_fmt:
    name: "check code format and linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
